### PR TITLE
806 improve documentation on exception handling when enumerating invocations

### LINKED ISSUE #806: Improve documentation on exception handling when enumerating invocations
It is not clear from the code how EnumerateLibraryDefinitionsResults acts if there’s no ValueExceptionHandler passed to it. Will it simply throw? If yes, any specific exceptions? Improve readability and documentation

https://firelyteam.slack.com/archives/C021G7NAN2J/p1744489513660349

### PR DESCRIPTION
**Pull request by baseTwo**
⚠️ Review and merge previous PR #805
⚠️ Review submodule [Integration Runner](https://github.com/FirelyTeam/Firely.Cql.Sdk.Integration.Runner/pull/40)

Here is a sample screenshot for the documentation for enumerating the invocations. The updated documentation is highlighted in orange.
image

### CODE REVIEW

**Comment by baseTwo** [comment]
Review #805 first

File: Demo/CqlApiExamples/Program.cs [hunk 1]
```diff
@@ -26,9 +26,9 @@ private static void Main(string[] args)
         // Create a logger factory via the Microsoft.Extensions.Logging API
         var loggerFactory = LoggerFactory.Create(builder => builder.AddConsole());
 
-        AddDuplicates(loggerFactory);
-        Add3And2Example(loggerFactory);
-        InvokeCqlExample(loggerFactory);
+        // AddDuplicates(loggerFactory);
```
Comment (ewoutkramer) [inline Demo/CqlApiExamples/Program.cs:29]: Are these supposed to remain commented out?

**Review by ewoutkramer — CHANGES_REQUESTED** [review]

File: Demo/CqlApiExamples/Program.cs (hunk 1 above)
Comment (baseTwo) [reply Demo/CqlApiExamples/Program.cs:29]: Will do in #821

**Review by ewoutkramer — APPROVED** [review]
