### PR TITLE
Combine DataRequirement components if they share the same type

### LINKED ISSUE #853: Aggregate DataRequirement components if overlapping
**Describe the bug**
"Implementations SHOULD aggregate data requirements intelligently (i.e. by collapsing overlapping data requirements)". See https://www.hl7.org/fhir/R4/library-operation-data-requirements.html

We should combine all data requirements if they share the same type.

### PR DESCRIPTION
**Pull request by alexzautke**
Fixes #853

### CODE REVIEW

File: Cql/Cql.Packaging/DataRequirementsAnalyzer.cs [hunk 1]
```diff
@@ -108,6 +108,47 @@ private bool Visit(
...
     }
 
+    private List<DataRequirement> Combine(List<DataRequirement> initialDataRequirements)
+    {
+        var result = new List<DataRequirement>();
+        var grouped = initialDataRequirements.GroupBy(r => r.Type);
+        foreach (var group in grouped)
+        {
+            var dr = group.First();
+            dr.MustSupportElement = [..group.SelectMany(g => g.MustSupportElement)];
```
Comment (ewoutkramer) [inline Cql/Cql.Packaging/DataRequirementsAnalyzer.cs]: Is this a fancty way of doing `group.SelectMany(...).ToList()` ?

File: Cql/Cql.Packaging/DataRequirementsAnalyzer.cs [hunk 2]
```diff
@@ -108,6 +108,47 @@ private bool Visit(
...
+            dr.MustSupportElement = dr.MustSupportElement.Aggregate(new List<FhirString>(), (acc, current) =>
+            {
+                if (!acc.Any(e => e.IsExactly(current))) acc.Add(current);
+                return acc;
+            }).ToList();
```
Comment (ewoutkramer) [inline Cql/Cql.Packaging/DataRequirementsAnalyzer.cs]: That's a `Distinct`, so `dr.MustSupportElement` = dr.MustSupportElement.Distinc().ToList()`?

Comment (ewoutkramer) [reply Cql/Cql.Packaging/DataRequirementsAnalyzer.cs]: On FhirString, that would need a good Equality operator, so, maybe this is better:

```
var baseComparer = EqualityComparer<Base>.Create((x, y) => x.IsExactly(y));
dr.MustSupportElement = dr.MustSupportElement.Distinct(baseComparer);
```

File: Cql/Cql.Packaging/DataRequirementsAnalyzer.cs [hunk 3]
```diff
@@ -108,6 +108,47 @@ private bool Visit(
...
+            dr.CodeFilter = dr.CodeFilter.Aggregate(new List<DataRequirement.CodeFilterComponent>(), (acc, current) =>
+            {
+                if (!acc.Any(e => e.IsExactly(current))) acc.Add(current);
+                return acc;
+            }).ToList();
+
+            dr.ProfileElement = [..group.SelectMany(g => g.ProfileElement)];
+            dr.ProfileElement = dr.ProfileElement.Aggregate(new List<Canonical>(), (acc, current) =>
+            {
+                if (!acc.Any(e => e.IsExactly(current))) acc.Add(current);
```
Comment (ewoutkramer) [inline Cql/Cql.Packaging/DataRequirementsAnalyzer.cs]: Same, you can reuse the `baseComparer`.

**Review by ewoutkramer — CHANGES_REQUESTED** [review]

File: Cql/Cql.Packaging/DataRequirementsAnalyzer.cs (hunk 1 above)
Comment (alexzautke) [reply Cql/Cql.Packaging/DataRequirementsAnalyzer.cs]: Yes, I copied that from you from the Visit method ;)

File: Cql/Cql.Packaging/DataRequirementsAnalyzer.cs (hunk 2 above)
Comment (alexzautke) [reply Cql/Cql.Packaging/DataRequirementsAnalyzer.cs]: I tried the Distinct before, but the EqualityComparer<Base> fails for me on comparing Canonicals with 
```
Test method CoreTests.TestDataRequirementsAnalyzer.ConvertRetrievesToDataRequirements threw exception: 
System.NotSupportedException: Specified method is not supported.
   at System.Collections.Generic.EqualityComparer`1.<>c.<Create>b__3_0(T _)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at System.Collections.Generic.HashSet`1.Add(T item)
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
```

The Aggregate is just the workaround for that as I didn't want to also introduce additional comparers.

Comment (ewoutkramer) [reply Cql/Cql.Packaging/DataRequirementsAnalyzer.cs]: It did that on me too. I looked at Microsoft's implementation to find out what was wrong. I needed to add a function for hashcodes too....not so trivial ;-)

**Review by ewoutkramer — APPROVED** [review]

**Review by baseTwo — APPROVED** [review]
