### PR TITLE
1142 MaxDepth exceeded when parsing JSON ELM for CMS measures  

### LINKED ISSUE #1142: [Bug] MaxDepth exceeded when parsing JSON ELM for CMS measures
# JSON Depth Limit Issue in ELM Deserialization

## Problem Description

When attempting to parse deeply nested ELM (Expression Logical Model) JSON files, specifically the **CMS133FHIRCataracts2040BCVA90Days.json** measure, the SDK would fail with a `JsonException` due to exceeding the default maximum depth limit of **64 levels**.

### Root Cause

The default `JsonDocumentOptions` and `JsonSerializerOptions` in .NET have a `MaxDepth` property that defaults to **64**. This limit exists to prevent stack overflow attacks and malicious JSON payloads. However, legitimate CMS clinical quality measures contain deeply nested expression trees that exceed this limit.

The CMS133 measure (Cataracts 20/40 BCVA 90 Days) contains complex nested queries and expressions that create a JSON structure deeper than 64 levels when serialized to ELM format.

### Error Encountered

```
JsonException: The reader's MaxDepth of 64 has been exceeded.
```

This error occurred when calling:
- `JsonNode.Parse(stream)` - Used during deserialization
- Internal JSON parsing operations within `System.Text.Json`

### Affected Code Locations

**File:** `Cql/Elm/Library-serialization.cs` (now `Cql/Elm/Serialization/LibraryJsonSerializer.cs`)

**Problem Areas:**

1. **JsonNode.Parse** - Did not specify `MaxDepth` configuration:
```csharp
// BEFORE (Failed on deep JSON)
var node = JsonNode.Parse(stream) ??
           throw new InvalidOperationException("JsonNode.Parse unexpectedly returned null.");
```

2. **JsonSerializerOptions** - Used `int.MaxValue` which could cause memory issues:
```csharp
// BEFORE (Potential memory issues)
var options = new JsonSerializerOptions
{
    MaxDepth = int.MaxValue,
    // ...
};
```

3. **Missing JsonDocumentOptions** - No configuration for document parsing depth

### Test File
**Path:** `Cql\CoreTests\Input\ELM\Libs\CMS133FHIRCataracts2040BCVA90Days.json`

### Test Method
**File:** `Cql\CoreTests\ElmSerializerTests.cs`  
**Method:** `Elm_Deserialize_Deep()`

```csharp
[TestMethod]
public void Elm_Deserialize_Deep()
{
    var originalElm = File.ReadAllText(Path.Combine("Input", "ELM", "Libs", "CMS133FHIRCataracts2040BCVA90Days.json"));
    var lib = Library.ParseFromJson(originalElm);
    var elm = lib.SerializeToJson();
    
    var expected = LibraryJsonSerializer.ParseToJsonNode(originalElm);
    var actual = LibraryJsonSerializer.ParseToJsonNode(elm);
    var errors = CompareNode(expected, actual);
    errors.RemoveAll(acceptable);
    
    Assert.AreEqual(0, errors.Count, message: string.Join("\n", errors));
    
    static bool acceptable(string s)
    {
        return AcceptableErrors.Any(s.Contains);
    }
}
```

This test verifies:
1. The deep JSON can be parsed without exceeding max depth
2. The library can be deserialized correctly
3. The library can be re-serialized back to JSON
4. The roundtrip maintains structural integrity

### PR DESCRIPTION
**Pull request by richfirely**
## Pull request overview

This PR addresses JSON parsing failures due to `MaxDepth` being exceeded when loading deep CMS ELM JSON libraries and adds regression coverage for such cases.

**Changes:**
- Introduced `LibraryJsonSerializer.ParseToJsonNode` to centralize `JsonNode` parsing with the custom `JsonDocumentOptions` (including the higher `MaxDepth`).
- Updated `Library.ParseFromJson(string)` and existing JSON round-trip tests to use the new parsing helper for consistent behavior with stream-based parsing.
- Added a new deep ELM serialization/deserialization test using a CMS133 JSON file to guard against regressions on highly nested ELM structures.

### CODE REVIEW

**Comment by baseTwo** [comment]
@richfirely , I fixed the parsing of a deep json for elm. The unit tests now fails based on something else

File: Cql/CoreTests/ElmSerializerTests.cs
Comment (richfirely) [inline Cql/CoreTests/ElmSerializerTests.cs]:
```suggestion
            "(value '[]') not found in actual object.",
// Java ELM includes default boolean values, but we omit them
"Expected key 'strict' (value 'false') not found in actual object."
```

File: Cql/CoreTests/ElmSerializerTests.cs [hunk 1]
```diff
@@ -41,7 +42,9 @@ public void Elm_Deserialize_TupleTypeSpecifier()
             // value), sometimes they are not for accessLevel. That's acceptable.
             "Unexpected key 'accessLevel' (value '\"Public\"') found in actual object.",
             //now removing empty values due to JAVA ELM having many empty arrays in the output
-            @"Expected key 'relationship' (value '[]') not found in actual object. At $.library.statements.def[6].expression.else.element[0].value."
+            "(value '[]') not found in actual object.",
+// Java ELM includes default boolean values, but we omit them
+"Expected key 'strict' (value 'false') not found in actual object."
```
Comment (richfirely) [inline Cql/CoreTests/ElmSerializerTests.cs:47]: Not sure if entirely correct, but this is the changes to allow the empty arrays and a new error popped up that looks like we can skip.

Comment (baseTwo) [reply Cql/CoreTests/ElmSerializerTests.cs]: @copilot , please apply this comment

**Comment by baseTwo** [comment]
@copilot open a new pull request to apply changes based on the comments in [this thread](https://github.com/FirelyTeam/firely-cql-sdk/pull/1133#pullrequestreview-3745322176)

**Review by ewoutkramer — APPROVED** [review]
