### PR TITLE
997 Enhance CQL processing with error handling and new features

### LINKED ISSUE #997: Add setting in PackagerCLI to fail fast (exit upon error)
The PackagerCLI does a best effort to continue processing a batch of items through various stages. Errors are ignored and logged as warnings in the log.

Add a setting to fail fast upon the first error.

### PR DESCRIPTION
**Pull request by baseTwo**
# Pull Request Overview

This PR enhances CQL processing capabilities by adding error handling controls and expanding functionality. The changes introduce an ExitOnError configuration option that allows users to control whether processing should halt on errors or continue with remaining items, providing more flexible error handling strategies.

### CODE REVIEW

File: Cql/PackagerCLI/Commands.CqlToFhir/CqlToFhirCommand.cs [hunk 1]
```diff
@@ -124,6 +125,7 @@ Override date output in FHIR library.
         (CanonicalRootUrl, [PackagingOptions.ConfigSection, nameof(PackagingOptions.CanonicalRootUrl)]),
         (OverrideUtcDateTime, [PackagingOptions.ConfigSection, nameof(PackagingOptions.OverrideDate)]),
         (JsonPretty, [ElmOptions.ConfigSection, nameof(ElmOptions.JsonPretty)]),
```
[the remark this answers is not in the document]
Comment (baseTwo) [reply Cql/PackagerCLI/Commands.CqlToFhir/CqlToFhirCommand.cs]: Fixed

File: Cql/PackagerCLI/Options/ElmOptions.cs [hunk 2]
```diff
@@ -16,5 +16,4 @@ public record ElmOptions : ElmToolkitConfig, IBindOptions
     static string IBindOptions.ConfigSection => ConfigSection;
 
     public string[] SkipFiles { get; init; } = [];
-    public bool JsonPretty { get; init; }
```
Comment (alexzautke) [inline Cql/PackagerCLI/Options/ElmOptions.cs:19]: Why remove this here?

Comment (baseTwo) [reply Cql/PackagerCLI/Options/ElmOptions.cs:19]: It's a duplicate, there is a single JsonPretty already on PacakgingOptions which maps to - - json-pretty

**Review by alexzautke — APPROVED** [review]
