### PR TITLE
670 20 Begin CQL, ELM and Runtime APIs

### LINKED ISSUE #670: Public API | Begin CQL, ELM and Runtime APIs
## Target Consumers of API:

- Basic: Developers using API as-is. We will write stable versioned API for this group.
- Advanced: Developers wanting to extend the API. This group may extend functionality of the API writing extension methods on the interfaces provided under namespaces ending with ".Extensibility". (May have to pick a better name at a later stage for this). These interfaces are not considered part of the basic API and not considered stable.
- CLI (Command Line Interface) Tooling Users. Those want to generate artifacts only using the command line packaging tool. 

## APIs
Split into multiple APIs: 
- CQL API 
  - Core
    - add CQL strings
    - convert CQL to ELM
    - access to generated ELM
  - Extensions
    - add CQL from files, directories, etc.
    - save ELM to directories
    - invoke runtime definitions (via ELM, then Runtime API)
- ELM API
  - Core
    - add ELM libraries
    - convert ELM -> C# -> .NET assemblies + debug symbols -> FHIR Resources (library, measure, etc.))

      At no point between ELM and the ultimate outputs is it allowed to modify or inject the intermediate artifacts, e.g. changing the C#, or adding additional DLLs into a FHIR resource is not allowed
    - access to generated C#, assemblies, debug symbols, FHIR Resources
    - ❓ signing assemblies
    - ❓ access to warnings and errors via property
  - Extensions
    - add ELM from CQL API output
    - add ELM from files, directories, etc.
    - save C# to directories
    - save assemblies to directories
    - save debug symbols to directories
    - save FHIR Resources to directories
    - invoke runtime definitions (via Runtime API)
- Runtime API
  - extract assemblies from FHIR Resources (Extension?)
  - add assembly bytes with optional debug symbols bytes
  - provide access to assemblies
  - allow dynamically invoking definitions given a library name/version and the definition name
  - DEBUGGING SUPPORT - The ability to step into the generated c# code when the assemblies contain debug symbols

## Considerations:
- Keeping it very simple for users of the API
- API divided into basic/public/stable and advanced/"internal"/beta
- ~Error handling will be available through an Errors property instead of exceptions~
- Error handling - allow best effort processing, ignoring errors.  Each stage 
- Single-threaded, synchronous operations
- Choosing specialized types (e.g. `DirectoryInfo`, `CqlVersionedIdentifier`) over strings
- ~Immutable compilation units~
- Using files, strings and byte arrays as input and output. No streams (considered advanced)
- Only focused on translating, not on introspection of libraries
- Extending the API possible with extension methods using "advanced" interfaces
- Advanced features available through interfaces and implemented as explicit in derived types
  - Introspection of cql or elm
  - Streams?
  - Internal access to services?

### PR DESCRIPTION
**Pull request by baseTwo**
Work for #670 

ℹ️ For the design, and considerations, please ready the description on the issue above.
ℹ️ Since this is a huge prototype, merges will be into a new side branch `develop-2.1`  which will be merged back into `develop-2.0` later.

This PR is a prototype for the CQL public API. To jump straight into the example usage of the API, go to the `Cql\CqlSdkPrototype\App\Program.cs` file.

## Bulky Update

This PR contains many changes to the internals of the current repo, that were necessary, e.g. removing C# code generation out of `AssemblyCompiler` and shifting that solely to `CSharpCodeGenerator`, and shifting options out of the constructors and moving them as arguments to the main methods in each service. Many of the tests have been updated to use the new API.

Many types were removed in the repo, reducing complexity. 73000 lines of code removed and 7000 new lines added.

Summary of changes:
- General
  - Removed classes: *Callbacks, *PostProcessor, *ServiceCollectionExtensions, *ServiceProviderExtensions and many *Options and *Options.Validator

- Test Projects
  - Use the *Api's as much as possible instead of accessing services directly. Still much to do and clean up here

- CqlSdkPrototype project 
  - This is a new project where the new design is prototyped. The code here will be distributed amongst the existing projects before merging back into develop-2.0

- Compiler
  - LibrarySet is now internal

- CodeGeneration.NET
  - AssemblyCompiler: Simplified by removing the concern to generate source code. Only compiles assemblies. Now capable of generating debug symbols embedded into assembies, or as separate pdb byte[]
  - LibrarySetCSharpCodeGenerator: Simplified by removing callback.

- PackagerCLI
  - Almost all InternalsVisibleTo the PackagerCLI project were removed

- Test.Measures.Demo project
  - Some tests didn't pass before, they are now fixed
  - This was not a problem before since the tests were not included in the build pipeline, however, now they are

...
 
## CQL SDK Service Dependencies
The dependency injection graph shows the simpler design than before

Simpler design
```mermaid
%%{init: {
    'themeVariables':{  
      'lineColor': '#888',
      'lineWidth': 4
}}}%%

classDiagram

    direction LR

    namespace Compiler {
        class LibrarySetExpressionBuilder { }    
        class LibraryExpressionBuilder { }    
        class ExpressionBuilder { }    
        class ExpressionBuilderSettings { }    
        class TupleBuilderCache { }
        class CqlContextBinder { }
        class CqlOperatorsBinder { }       
    }

    namespace CodeGeneration {
        class TypeToCSharpConverter { }
        class CSharpCodeGenerator { }
        class AssemblyCompiler { }
    }

    namespace Packaging {
        class ResourcePackager { }
    }

    namespace Abstraction {
        class TypeResolver { }
    }

    namespace Runtime {
        class BaseTypeResolver { }
    }

    namespace Fhir {
        class FhirTypeResolver { }
        class ModelInspector { }
    }

    namespace Conversion {
        class TypeConverter { }
    }

    %% Style Scoped Types as Cyan

    style LibrarySetExpressionBuilder fill:#055
    style LibraryExpressionBuilder fill:#055
    style ExpressionBuilder fill:#055
    style TupleBuilderCache fill:#055
    
    %% Inheritance  

    BaseTypeResolver --> TypeResolver : inherits
    FhirTypeResolver --> BaseTypeResolver : inherits
    
    %% Dependencies                                                 

    LibraryExpressionBuilder ..> LibrarySetExpressionBuilder : injected

    ExpressionBuilder ..> LibraryExpressionBuilder : injected

    TypeResolver ..> ExpressionBuilder : injected
    CqlOperatorsBinder ..> ExpressionBuilder : injected
    TupleBuilderCache ..> ExpressionBuilder : injected
    CqlContextBinder ..> ExpressionBuilder : injected
    ExpressionBuilderSettings ..> ExpressionBuilder : injected

    TypeResolver ..> CqlOperatorsBinder : injected
    TypeConverter ..> CqlOperatorsBinder : injected

    ModelInspector ..> TypeConverter : injected  

    TypeToCSharpConverter ..> CSharpCodeGenerator : injected
    TypeResolver ..> CSharpCodeGenerator : injected

    TypeResolver ..> AssemblyCompiler : injected

    TypeResolver ..> ResourcePackager : injected
```

### CODE REVIEW

**Comment by and-hus** [comment]
Just some general thoughts about the considerations, which I am not sure if they are implicitly covered (I haven't checked the code yet...):

I assume that the term "API" covers both: Libraries (nuget packages) to add functionality to larger projects or services and command line tools (e.g. nuget packages installed as a dotnet tools). Where the command line tool is basically a wrapper around the library. I assume that it's planned to create both - right?

Working on files is definitively the most important use case.
But what do you think about an abstraction layer to enable support for different sources or sinks than just files, e.g. a database? It might be worth the effort to add this abstraction layer early on to be prepared for different use cases than just file based actions. This might become handy if you want to used the SDK in a larger project - e.g. integrate it into a FHIR server or another service.

Nice idea to design a fluent interface - I like the approach.
It probably already serves the purpose of the abstraction layer I mentioned above...

One thought about execution of libraries. I think it would be nice to have both options:
- Execute the whole library, so run all expressions and return a dictionary with the results  
  Basically what the `Run()` method in the AssemblyLoadContextExtensions implements
- Execute just a single expression and return just this result  
  So something like `object? asm.RunExpression(library, version, context, expression)`

File: Cql/CqlSdkPrototype/Program.cs [hunk 1]
```diff
@@ -0,0 +1,387 @@
...
+            var fileName = Path.Combine(directory.FullName, $"{libraryName}.dll");
+            File.WriteAllBytes(fileName, assemblyBinary);
+            Console.WriteLine($"Saved assembly binary to file: {fileName}");
+        }
+        return this;
+    }
+}
+
+
+public readonly record struct ElmVersionedIdentifier
```
Comment (and-hus) [inline Cql/CqlSdkPrototype/Program.cs]: I think this struct is generic enough to be used in other contexts then just for the Elm, e.g. for the FHIR library resources etc. So what do you think about renaming this to just `VersionedIdentifier`?

File: Cql/CqlSdkPrototype/Program.cs [hunk 2]
```diff
@@ -0,0 +1,387 @@
...
+
+    public string? Version { get; init; }
+
+    public void Deconstruct(out string name, out string? version)
+    {
+        name = Name;
+        version = Version;
+    }
+
+    public static ElmVersionedIdentifier ParseString(string text)
```
Comment (and-hus) [inline Cql/CqlSdkPrototype/Program.cs]: To be consistend with `FromNameAndVersion()` and `FromVersionedIdentifier()` I would propose to rename this method to `FromString()` - what do you think?

**Comment by and-hus** [comment]
Regarding the API for the ElmCompiler, what do you think about using the builder pattern, so something along these lines:

```csharp
var elmCompiler = 
          ElmCompilerBuilder
                .New
                .WithInputFile(elmInDir, ElmVersionedIdentifier.FromNameAndVersion("FHIRHelpers"))
                .WithInputFolder(elmInDir, new EnumerationOptions() { RecurseSubdirectories = false })
                .WithCSharpOutputFolder(csharpOutDir)
                .WithAssemblyOutputFolder(dllOutDir)
                .Build();
                
elmCompiler.Compile();
```

File: Cql/CqlSdkPrototype/Program.cs (hunk 1 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Program.cs]: There is already a VersionedIdentifier as part of the ELM xml types. I didn't want to change it just yet for the prototype, might do that later

File: Cql/CqlSdkPrototype/Program.cs (hunk 2 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Program.cs]: I changed this to just Parse

**Comment by baseTwo** [comment]
> Regarding the API for the ElmCompiler, what do you think about using the builder pattern, so something along these lines:
> 
> ```cs
> var elmCompiler = 
>           ElmCompilerBuilder
>                 .New
>                 .WithInputFile(elmInDir, ElmVersionedIdentifier.FromNameAndVersion("FHIRHelpers"))
>                 .WithInputFolder(elmInDir, new EnumerationOptions() { RecurseSubdirectories = false })
>                 .WithCSharpOutputFolder(csharpOutDir)
>                 .WithAssemblyOutputFolder(dllOutDir)
>                 .Build();
>                 
> elmCompiler.Compile();
> ```

I have considered a builder pattern, but I really want to be able to modify the "ElmCompilation" even after compilation. (Think about running this for the Visual Studio plugin which does incremental builds, adding/removing files even after a compile).

We want to be able to add/remove files, compile, and repeat

**Comment by baseTwo** [comment]
Since this PR size is getting big, I'm splitting up the work into more sub tasks

File: Cql/CqlSdkPrototype/Cql/CqlApi.cs [hunk 3]
```diff
@@ -0,0 +1,159 @@
...
+using CqlTranslationEntriesMap = System.Collections.Immutable.ImmutableDictionary<
+    CqlVersionedLibraryIdentifier,
+    CqlTranslationEntry>;
+
+public class CqlApi(CqlApiOptions options) :
+    ICqlApiExtensible<CqlApi>
+{
+    internal ICqlApiExtensible<CqlApi> AsExtensible() => this;
+    TResult ICqlApiExtensible<CqlApi>.UseLogger<TResult>(Func<CqlApi, ILogger<CqlApi>, TResult> action) => action(this, _state.Logger);
+    public static CqlApi Create(CqlApiOptions? options = null) => new(options ?? CqlApiOptions.Default);
```
Comment (and-hus) [inline Cql/CqlSdkPrototype/Cql/CqlApi.cs]: The class has both, a public primary constructor and this static factory method. 
So there are basically two ways to create an instance of this class - is this intentionally? 
To have just one controlled way for instantiation, I would propose to make the constructor private which leaves the static factory method as the only way to create an instance. What do you think?

File: Cql/CqlSdkPrototype/App/Program.cs [hunk 4]
```diff
@@ -0,0 +1,265 @@
...
+namespace CqlSdkPrototype.App;
+
+internal class Program
+{
+    static void Main(string[] args)
+    {
+        // CONSIDERATIONS:
+        // - Encapsulate the creation of the service provider
+        // - Move any options such as the AssembliesDebugMode and Models to the Cql- or ElmApi instead of via the hosted IOptions<T>
+        // - Should we keep the dependency on Microsoft's ILogger or should we create our own logging abstraction?
```
Comment (and-hus) [inline Cql/CqlSdkPrototype/App/Program.cs]: Out of curiosity: 
What's the problem with Microsoft's ILogger<> ? 
Why are you considering to create your own logging abstraction? What are you trying to achieve that is not possible with ILogger?

Comment (baseTwo) [reply Cql/CqlSdkPrototype/App/Program.cs]: I use Microsoft's logging framework in the current PR.

Comment (baseTwo) [reply Cql/CqlSdkPrototype/App/Program.cs]: I should move out my thoughts from the code though,. They're all in the parent issue's description  #670

Comment (baseTwo) [reply Cql/CqlSdkPrototype/App/Program.cs]: I am using ILogProvider[] in the LoggingOptions, but I think it should be changed to ILoggerFactory instead.

Comment (and-hus) [reply Cql/CqlSdkPrototype/App/Program.cs]: I agree - I am also more used to `ILogger<>` or `ILoggerFactory`...

From the perspective of a user/consumer of the API, I would expect the API to accept either a `ILogger<TCategoryName>` parameter or an `ILoggerFactory`. So something like

```csharp
 public class CqlApi(){

    public static CqlApi Create(ILogger<CqlApi> logger = null);
 }
```

or

```csharp
 public class CqlApi(){

    public static CqlApi Create(ILoggerFactory loggerFactory = null);
 }
```

See e.g. [here](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging-library-authors) for some guidance on when to use which approach.

But I assume that I'm just not getting the point why the current setup is required  ;-)

Comment (baseTwo) [reply Cql/CqlSdkPrototype/App/Program.cs]: The API's create their own ServiceProvider which will create ILogger for all the internal services required including the API's. When setting up the ServiceProvider, it needs to know how to set up the LoggingBuilder. This is where the LoggingOptions comes in.

Comment (baseTwo) [reply Cql/CqlSdkPrototype/App/Program.cs]: I'm looking now if it's possible to only use ILoggerFactory in LoggingOptions, instead of passing in ILoggerProvider[] and the log filtering delegate.

Comment (and-hus) [reply Cql/CqlSdkPrototype/App/Program.cs]: Yes - I think that would be good and would allow the consumers of the API to use standard Microsoft Logging setups or 3rd party log providers like Serilog which typically provide dependency injection for `ILogger<>` or `ILoggerFactory` - I am not sure how this would work with `ILoggerProvider[]` ...

Comment (baseTwo) [reply Cql/CqlSdkPrototype/App/Program.cs]: Ok, ILoggerFactory was the correct choice. Please see changes in the commit.

Comment (baseTwo) [reply Cql/CqlSdkPrototype/App/Program.cs]: Setting up up logging now looks like this

```csharp
        // This would be set up in the consumers startup logic
        using var serviceProvider =
            new ServiceCollection()
                .AddLogging(lb => lb
                  .ClearProviders()
                  .AddProvider(new ColorConsoleLoggerProvider())
                  .AddFilter((category, _) => category?.Contains(value: nameof(CqlSdkPrototype)) ?? false))
                .BuildServiceProvider();

        // ILoggerFactory would be available through constructor dependency injection, and not directly from IServiceProvider
        var loggingOptions = new LoggingOptions(LoggerFactory: serviceProvider.GetRequiredService<ILoggerFactory>());

        var cqlApiOptions = new CqlApiOptions(
            LoggingOptions: loggingOptions,
            Models: [Models.ElmR1, Models.Fhir401]);

        var cqlApi = new CqlApi(cqlApiOptions);

```

File: Cql/CoreTests/PrimitiveTests.cs [hunk 5]
```diff
@@ -3405,29 +3407,18 @@ public void Collapse_Containing_Null()
...
+
+            var loggerFactory = new ServiceCollection()
+                                .AddDebugLogging()
+                                .BuildServiceProvider()
+                                .GetRequiredService<ILoggerFactory>();
+            new ElmApi(loggerFactory)
+                .AddElmLibraries(librarySet)
+                .Compile();
+
+            Assert.IsTrue(true);
```
Comment (ewoutkramer) [inline Cql/CoreTests/PrimitiveTests.cs:3421]: Does this test that the Compile() does not throw? Can we somehow make that more explicit (maybe FluentAssertions DoesNotThrow?)

File: Cql/Cql.Abstractions/ISingleton.cs [hunk 6]
```diff
@@ -13,4 +13,15 @@ public interface ISingleton<out TSelf>
     /// Gets the instance of the implementing class.
     /// </summary>
     static virtual TSelf Instance { get; } = Activator.CreateInstance<TSelf>();
+}
+
+/// <summary>
+/// Represents an interface for a singleton pattern.
+/// </summary>
+public interface ISingleton
```
Comment (ewoutkramer) [inline Cql/Cql.Abstractions/ISingleton.cs]: Is this useful?

File: Cql/Cql.CqlToElm/Visitors/TimingExpressionVisitor.cs [hunk 7]
```diff
@@ -13,6 +13,8 @@ namespace Hl7.Cql.CqlToElm.Visitors
 {
     internal partial class ExpressionVisitor
     {
+        internal static bool EnableDebugAssertions = true;
```
Comment (ewoutkramer) [inline Cql/Cql.CqlToElm/Visitors/TimingExpressionVisitor.cs:16]: Why is this on TimingExpressionVisitor specifically?

File: Cql/Cql.Packaging/FhirResourceWriterOptions.cs [hunk 8]
```diff
@@ -1,13 +1,13 @@
-﻿/*
+﻿/*/*
  * Copyright (c) 2024, NCQA and contributors
  * See the file CONTRIBUTORS for details.
  *
  * This file is licensed under the BSD 3-Clause license
  * available at https://raw.githubusercontent.com/FirelyTeam/firely-cql-sdk/main/LICENSE
- */
+ #1#
```
Comment (ewoutkramer) [inline Cql/Cql.Packaging/FhirResourceWriterOptions.cs:7]: Would you not want to delete this file instead of commenting it out completely?

File: Cql/Cql.Runtime/EmptyDisposable.cs [hunk 9]
```diff
@@ -0,0 +1,10 @@
+﻿using System;
+
+namespace Hl7.Cql.Runtime;
+
+internal readonly record struct EmptyDisposable : IDisposable
```
Comment (ewoutkramer) [inline Cql/Cql.Runtime/EmptyDisposable.cs]: Curious to learn later what you are using this for....

File: Cql/CqlSdkPrototype/Cql/CqlApi.cs [hunk 10]
```diff
@@ -0,0 +1,135 @@
...
+using CqlSdkPrototype.Internal;
+using Hl7.Cql.CqlToElm;
+using Hl7.Cql.Runtime;
+using Microsoft.Extensions.Logging.Abstractions;
+
+namespace CqlSdkPrototype.Cql;
+
+using CqlApiStateEntryDictionary = ImmutableDictionary<CqlVersionedLibraryIdentifier, CqlApiStateEntry>;
+
+public class CqlApi :
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Cql/CqlApi.cs:11]: I am not in love with the name "CqlApi".  Just this morning I confused it with "a library to work with Cql", but it is instead a library to get from Cql to Elm, and the name kind of does not show that. Also, mentioning the term "Api" explicitly feels superfluous. Would CqlToElm or CqlCompiler (well, I guess we have that in the lower-level API already) be something?  CqlConverter, CqlTransformer, CqlProcessor..... CqlSomething ;-)

File: Cql/CqlSdkPrototype/Cql/CqlApi.cs [hunk 11]
```diff
@@ -0,0 +1,135 @@
...
+    internal CqlApi(CqlApiState state) => _state = state; // Might make this public later. Used for testing now.
+
+    public CqlApi(
+        ILoggerFactory? loggerFactory = null,
+        CqlApiOptions? options = null) : this(CqlApiState.Create(loggerFactory ?? NullLoggerFactory.Instance, options ?? CqlApiOptions.Default))
+    {}
+
+    #region State
+
+    private CqlApiState _state;
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Cql/CqlApi.cs]: I know you initially had CqlApi be read-only, and now it's a big state object in CqlApi, that's almost 1-on-1 with the CqlApi. What was the advantage again of keeping the CqlApi mutable, but the state inside immutable?

File: Cql/CqlSdkPrototype/Cql/CqlApiState.cs [hunk 12]
```diff
@@ -0,0 +1,142 @@
...
+    {
+        get => _options;
+        init
+        {
+            if (ReferenceEquals(_options, value))
+                return;
+
+            ServiceProvider?.Dispose();
+
+            _options = value;
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Cql/CqlApiState.cs]: With this many side-effects, I'd lean towards `SetOptions()`. Which you probably avoided to be able to use `with`?

File: Cql/CqlSdkPrototype/Cql/CqlApiState.cs [hunk 13]
```diff
@@ -0,0 +1,142 @@
...
+                foreach (var modelInfo in modelInfos)
+                    modelProvider.Add(modelInfo);
+            };
+        }
+    }
+
+    private static void SuppressCqlDebugAssertions()
+    {
+        // This is really annoying in debug mode
+        ExpressionVisitor.EnableDebugAssertions = false;
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Cql/CqlApiState.cs]: I think these were left-over debug statements that we might be able to just remove. But, yes, we'd need to double check with Evan.

File: Cql/CqlSdkPrototype/Cql/CqlApiState.cs [hunk 14]
```diff
@@ -0,0 +1,142 @@
...
+
+        if (EntriesBuilder.TryGetValue(libVer, out var entry))
+        {
+            if (entry.ElmLibraryBuilder is {} lb)
+            {
+                libraryBuilder = lb;
+                return true;
+            }
+
+            ;
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Cql/CqlApiState.cs]: I've seen a few empty colons like these, is that on purpose?

File: Cql/CqlSdkPrototype/Cql/Extensibility/CqlApiStateEntry.cs [hunk 15]
```diff
@@ -0,0 +1,9 @@
+﻿using CqlSdkPrototype.Infrastructure;
+using Hl7.Cql.CqlToElm;
+using Hl7.Cql.Elm;
+
+namespace CqlSdkPrototype.Cql.Extensibility;
+
+public readonly record struct CqlApiStateEntry(CqlLibraryString CqlLibraryString, Library? ElmLibrary = null) {
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Cql/Extensibility/CqlApiStateEntry.cs:7]: CqlApiState is internal, does this need to be public?

Comment (ewoutkramer) [reply Cql/CqlSdkPrototype/Cql/Extensibility/CqlApiStateEntry.cs:7]: If this is a public facing struct, then we should give it a sexier name, something that says what it is, as the current name is too abstract to tell the user about its function.

File: Cql/CqlSdkPrototype/Cql/Internal/ICqlApiInternal.cs [hunk 16]
```diff
@@ -0,0 +1,9 @@
+﻿using CqlSdkPrototype.Cql.Extensibility;
+
+namespace CqlSdkPrototype.Cql.Internal;
+
+internal interface ICqlApiInternal<TCqlApi> : ICqlApiExtendable<TCqlApi>
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Cql/Internal/ICqlApiInternal.cs:8]: Maybe explain why there is an internal version with a few lines of comments.

File: Cql/CqlSdkPrototype/Elm/ElmApi.cs [hunk 17]
```diff
@@ -0,0 +1,194 @@
...
+
+namespace CqlSdkPrototype.Elm;
+
+using ElmApiStateEntryDictionary = ImmutableDictionary<CqlVersionedLibraryIdentifier, ElmApiStateEntry>;
+
+public class ElmApi :
+    IElmApiExtendable<ElmApi>,
+    IElmApiInternal<ElmApi>
+{
+    public ElmApi(
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Elm/ElmApi.cs:18]: Same mixed feelings as for "CqlApi".

File: Cql/CqlSdkPrototype/Elm/ElmApi.cs [hunk 18]
```diff
@@ -0,0 +1,194 @@
...
+        return hasChanged
+                   ? WithEntries(entries: entries.ToImmutable())
+                   : this;
+    }
+
+    #endregion
+
+    #region Processing
+
+    public ElmApi Compile()
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Elm/ElmApi.cs:85]: That's a big function!

File: Cql/CqlSdkPrototype/Elm/ElmApiScopedState.cs [hunk 19]
```diff
@@ -0,0 +1,10 @@
+﻿using Hl7.Cql.Compiler;
+
+namespace CqlSdkPrototype.Elm;
+
+internal class ElmApiScopedState(IServiceScope scope) : IDisposable
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Elm/ElmApiScopedState.cs:5]: What are we using scoped state for?

File: Cql/CqlSdkPrototype/Elm/ElmApiState.cs [hunk 20]
```diff
@@ -0,0 +1,100 @@
...
+        init
+        {
+            if (ReferenceEquals(_options, value))
+                return;
+
+            ServiceProvider?.Dispose();
+
+            _options = value;
+
+            var services = new ServiceCollection();
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Elm/ElmApiState.cs:50]: See CqlApiOptions.Options

File: Cql/CqlSdkPrototype/Elm/Extensions/ElmApiExtensions.Cql.cs [hunk 21]
```diff
@@ -0,0 +1,17 @@
...
+using CqlSdkPrototype.Runtime.Extensions;
+
+namespace CqlSdkPrototype.Elm.Extensions;
+
+public static partial class ElmApiExtensions
+{
+    public static ElmApi Compile(
+        this CqlApi cqlApi)
+    {
+        return cqlApi
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Elm/Extensions/ElmApiExtensions.Cql.cs:11]: Nice!

File: Cql/CqlSdkPrototype/GlobalUsings.cs [hunk 22]
```diff
@@ -0,0 +1,10 @@
+// Global using directives
+
+global using System.Collections.Immutable;
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/GlobalUsings.cs:3]: Yeah, add System!

File: Cql/CqlSdkPrototype/Infrastructure/CqlLibraryString.cs [hunk 23]
```diff
@@ -0,0 +1,58 @@
...
+    public static CqlLibraryString Empty { get; } = new(CqlVersionedLibraryIdentifier.Empty, string.Empty);
+
+    public static CqlLibraryString FromIdentifierAndString(
+        CqlVersionedLibraryIdentifier versionedLibraryIdentifier,
+        string cqlContent)
+    {
+        return new CqlLibraryString(versionedLibraryIdentifier, cqlContent);
+    }
+
+    [GeneratedRegex("""
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Infrastructure/CqlLibraryString.cs:21]: Good to have a comment with a reference to where this regex can be found in the CQL documentation here

File: Cql/CqlSdkPrototype/Internal/Directories.cs [hunk 24]
```diff
@@ -0,0 +1,56 @@
...
+            current = current.Parent;
+        }
+
+        throw new InvalidOperationException("Could not find ancestor directory from search criteria.");
+    }
+
+    public static DirectoryInfo CurrentDirectory { get; } = new(Directory.GetCurrentDirectory());
+    public static DirectoryInfo CurrentSolutionDirectory { get; } = FindAncestor(CurrentDirectory, d => d.EnumerateFiles("*.sln?").Any());
+    public static DirectoryInfo CurrentProjectDirectory { get; } = FindAncestor(CurrentDirectory, d => d.EnumerateFiles("*.csproj").Any());
+    public static DirectoryInfo AuthoringProjectDirectory => CurrentSolutionDirectory.CreateSubdirectory("Demo").CreateSubdirectory("Measures.Authoring");
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Internal/Directories.cs:32]: It's a bit too much side effect for my taste to create a directory when reading a property, can this property be named GetAuthoringProjectDirectory()?  This applies to the other props here as well of course!

File: Cql/CqlSdkPrototype/Internal/InternalExtensions.cs [hunk 25]
```diff
@@ -0,0 +1,108 @@
...
+
+    public static Assembly LoadFromBytes(this AssemblyLoadContext assemblyLoadContext, byte[] assembly, byte[]? symbols = null)
+    {
+        using var assemblyStream = new MemoryStream(assembly);
+        var symbolsStream = symbols is {Length:>0} ? new MemoryStream(symbols) : null;
+        using var symbolsStreamDisposable = symbolsStream as IDisposable ?? new EmptyDisposable();
+        return assemblyLoadContext.LoadFromStream(assemblyStream, symbolsStream);
+    }
+
+    public static IEnumerable<TR> SelectWhereNotNull<T, TR>(
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Internal/InternalExtensions.cs:33]: Would it be far-fetched to have a company-wide library with this stuff? I need it too.  You have done this in your previous job, right?

File: Cql/CqlSdkPrototype/Internal/Maybe.cs [hunk 26]
```diff
@@ -0,0 +1,77 @@
+﻿namespace CqlSdkPrototype.Internal;
+
+internal readonly record struct Maybe
+{
+    public static Maybe NoValue => default;
+    public static Maybe<T> Of<T>(T value) => new(value);
+}
+
+internal readonly record struct Maybe<T>(T Value)
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Internal/Maybe.cs:9]: I have just removed a similar `Result<T>` from the FHIR Plugin. I love the concept, but it's just not common C# enough to have it in the public interface. And I think it will remain a curiosity within your code. Alas, I'd love to use it.

File: Cql/CqlSdkPrototype/Logging/ColorConsoleLogger.cs [hunk 27]
```diff
@@ -0,0 +1,184 @@
+﻿using Microsoft.Extensions.Logging.Abstractions;
+using System.Collections.Concurrent;
+using System.Globalization;
+using System.Text.RegularExpressions;
+using EnumerableExtensions = Hl7.Cql.Abstractions.Infrastructure.EnumerableExtensions;
+
+namespace CqlSdkPrototype.Logging;
+
+public sealed partial class ColorConsoleLogger(string categoryName, ColorConsoleLoggerProvider provider) : ILogger
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Logging/ColorConsoleLogger.cs:9]: Does this need to be public?

File: Cql/CqlSdkPrototype/Runtime/Extensions/RuntimeApiExtensions.Cql.cs [hunk 28]
```diff
@@ -0,0 +1,33 @@
...
+        where TCqlApi : ICqlApiExtendable<TCqlApi>
+    {
+        var elmApiOptions = new ElmApiOptions(ProcessBatchItemExceptionHandling: cqlApi.Options.ProcessBatchItemExceptionHandling);
+        if (configureOptions is not null) elmApiOptions = configureOptions(elmApiOptions);
+        var elmApi = new ElmApi(cqlApi.LoggerFactory, elmApiOptions).AddElmFromCqlApi(cqlApi);
+        return elmApi;
+    }
+
+#pragma warning disable RS0026
+    public static RuntimeScope CreateRuntimeScope(
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Runtime/Extensions/RuntimeApiExtensions.Cql.cs:22]: As a "new" user, the first question that comes up is: "What's a RuntimeScope and why do I need it?".  When would I call CreateRuntimeScope?

File: Cql/CqlSdkPrototype/Runtime/Extensions/RuntimeApiExtensions.RuntimeScope.cs [hunk 29]
```diff
@@ -0,0 +1,79 @@
...
+
+namespace CqlSdkPrototype.Runtime.Extensions;
+
+public static partial class RuntimeApiExtensions
+{
+    public static IEnumerable<(CqlVersionedLibraryIdentifier library, string declarationName, Func<object?> getResult)> EnumerateLibrarySetDefinitionsResults(
+        this RuntimeScope scope,
+        CqlContext cqlContext)
+    {
+        foreach (var (libId, lib) in scope.Libraries)
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Runtime/Extensions/RuntimeApiExtensions.RuntimeScope.cs:15]: Shouldn't this function call `EnumerateLibraryDefinitionsResults` in the foreach, instead of duplicating its code?

File: Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs [hunk 30]
```diff
@@ -0,0 +1,81 @@
...
+            return false;
+        }
+
+        libraryInvoker = new LibraryInvoker_2_0_8_0(asILibrary);
+        return true;
+    }
+
+    public static bool SupportsVersion(Version cqlToolVersion)
+    {
+        return cqlToolVersion.IsBetween(new Version(2, 0, 8), new Version(2, 1));
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs]: Do we make a newer version of this class when the generated libraries change, and in the mean time keep updating the upper boundary for every new release?

File: Cql/PackagerCLI/DependencyInjection/PackagerCLiLoggingBuilderExtensions.cs [hunk 31]
```diff
@@ -80,6 +75,6 @@ public static ILoggingBuilder AddPackagerCLiLogging(
             /* 6 */
             LogLevel.None => /* n/a */ null,
             // @formatter: on
-            _ => throw new UnsupportedSwitchCaseError(logLevel, typeof(LogLevel).FullName).ToException(),
+            _ => throw new ArgumentOutOfRangeException(nameof(logLevel), logLevel, "Invalid LogLevel."),
```
Comment (ewoutkramer) [inline Cql/PackagerCLI/DependencyInjection/PackagerCLiLoggingBuilderExtensions.cs]: Or use the new standard .NET SwitchExpressionException?

File: Demo/Test.Measures.Demo/MeasuresTest.cs [hunk 32]
```diff
@@ -102,70 +106,63 @@ public void BCSEHEDIS2022_Numerator_FromElm()
...
+            CqlContext context)
+        {
+            return scope
+                   .EnumerateLibraryDefinitionsResults(context, CqlVersionedLibraryIdentifier.Parse($"{lib}-{version}"))
+                   .ToDictionary(t => t.definition, t => t.getResult());
+        }
+
         [UsedImplicitly]
-        public static AssemblyLoadContext LoadResources(
+        public static RuntimeScope CreateRuntimeScopeFromFhirResourceFile(
```
Comment (ewoutkramer) [inline Demo/Test.Measures.Demo/MeasuresTest.cs:120]: What did the RuntimeScope add to AssemblyLoadContext that requires this extra concept of a scope?  (sorry, it's hard to look back in such a big PR into files that I have already reviewed....)

File: Demo/Test.Measures.Demo/TestBase.cs [hunk 33]
```diff
@@ -1,51 +1,4 @@
...
-                    valueSets.AddRange(bundle.Entry.Select(e => e.Resource).OfType<ValueSet>());
-                else if (resource is ValueSet valueSet)
-                    valueSets.Add(valueSet);
-            }
-            var vsd = valueSets.ToValueSetDictionary(false);
-            return vsd;
-        }
- 
-    }
+    public abstract class TestBase;
```
Comment (ewoutkramer) [inline Demo/Test.Measures.Demo/TestBase.cs]: Just there to avoid compilation errors?

File: Cql/CqlSdkPrototype/Cql/Extensibility/ICqlApiExtendable.cs [hunk 34]
```diff
@@ -0,0 +1,14 @@
+﻿using CqlSdkPrototype.Infrastructure;
+
+namespace CqlSdkPrototype.Cql.Extensibility;
+
+public interface ICqlApiExtendable<TCqlApi>
```
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Cql/Extensibility/ICqlApiExtendable.cs:5]: What's the advantage of doing this over just writing extensions again the CqlApi class?

File: Cql/CqlSdkPrototype/Cql/CqlApi.cs (hunk 10 above)
Comment (ewoutkramer) [inline Cql/CqlSdkPrototype/Cql/CqlApi.cs:11]: Now that the SDK comes closer to being finzalized, we should enable the check again that all public members need documentation, since there's tons of public members without it now!

**Review by ewoutkramer — CHANGES_REQUESTED** [review]

File: Cql/CoreTests/PrimitiveTests.cs (hunk 5 above)
Comment (baseTwo) [reply Cql/CoreTests/PrimitiveTests.cs:3421]: It does throw by default. The options has a flag to set the exception handling. We can write an extension method to make it easier to change, but these convenience methods can come later. Issue #697

File: Cql/Cql.Abstractions/ISingleton.cs (hunk 6 above)
Comment (baseTwo) [reply Cql/Cql.Abstractions/ISingleton.cs]: I'll remove the non-generic one, since it's not being used

File: Cql/Cql.CqlToElm/Visitors/TimingExpressionVisitor.cs (hunk 7 above)
Comment (baseTwo) [reply Cql/Cql.CqlToElm/Visitors/TimingExpressionVisitor.cs:16]: There are two classes in the cql to elm package that has many debug assertions, of which this type is one. Not sure why asserts were used in the original PR, but i needed a quick way to disable them globally without changing existing behaviour. I suppose these assertions need to be cleaned up. We have to speak to @EvanMachusak about it. I added it as an item to #674

File: Cql/Cql.Runtime/EmptyDisposable.cs (hunk 9 above)
Comment (baseTwo) [reply Cql/Cql.Runtime/EmptyDisposable.cs:5]: Example usage below, shows the use of an IDisposable that might be null based on a condition, but that would not be allowed in a using inline scope. 

```csharp
 using var codeStream = new MemoryStream();
 MemoryStream? pdbStream = debugInformationFormat == AssemblyCompilerDebugInformationFormat.PortablePdb ? new MemoryStream() : null;
 using var pdbStreamDisposable = pdbStream as IDisposable ?? new EmptyDisposable();
```

File: Demo/Test.Measures.Demo/MeasuresTest.cs (hunk 32 above)
Comment (baseTwo) [reply Demo/Test.Measures.Demo/MeasuresTest.cs:120]: RuntimeScope encapsulates AssemblyLoadContext, which is disposable, so the RuntimeScope must be disposed when invocation is completed on it, so that the assemblies may unload..

File: Demo/Test.Measures.Demo/TestBase.cs (hunk 33 above)
Comment (baseTwo) [reply Demo/Test.Measures.Demo/TestBase.cs]: I'll remove the base type, since it no longer contains any class members, and there is only one test that derived from it

File: Cql/CqlSdkPrototype/Cql/CqlApi.cs (hunk 10 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Cql/CqlApi.cs:11]: - #675

File: Cql/CqlSdkPrototype/Cql/Extensibility/ICqlApiExtendable.cs (hunk 34 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Cql/Extensibility/ICqlApiExtendable.cs:5]: At the moment no advantage, because there is no derived type on CqlApi. I have already thought of another way to do the fluent style as discussed. Issue #697

File: Cql/Cql.Packaging/FhirResourceWriterOptions.cs (hunk 8 above)
Comment (baseTwo) [reply Cql/Cql.Packaging/FhirResourceWriterOptions.cs:7]: I want to keep this logic readily available when I'm writing the PackagerAPI. After that I'll deleted it before all goes back into the main branch

File: Cql/CqlSdkPrototype/Cql/CqlApi.cs (hunk 10 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Cql/CqlApi.cs:11]: I agree, but I couldn't come up with a good name yet. 

 My thoughts around keeping the name general is that, the instance CqlApi or ElmApi serves as the starting point of what you want to do, not what you want to do. That's because there are many extension methods on it that makes it convenient to go through all the stages of the pipeline and produce output. 
 
 Ideas?

File: Cql/CqlSdkPrototype/Cql/CqlApi.cs (hunk 11 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Cql/CqlApi.cs]: In functional programming, the data object should only contain the data, and external to it, a function will create a new state object. In this case, those functions are in the API type, and the extension methods to the API type

File: Cql/CqlSdkPrototype/Cql/CqlApiState.cs (hunk 13 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Cql/CqlApiState.cs]: To be cleaned up in  #674

File: Cql/CqlSdkPrototype/Cql/CqlApiState.cs (hunk 14 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Cql/CqlApiState.cs]: I forgot to take it out, I was stepping through the code an needed a breakpoint before leaving the scope

File: Cql/CqlSdkPrototype/Elm/ElmApiScopedState.cs (hunk 19 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Elm/ElmApiScopedState.cs:5]: Encapsulates the service provider scope and to get access to the scoped services

Comment (baseTwo) [reply Cql/CqlSdkPrototype/Elm/ElmApiScopedState.cs:5]: I want to remove all scoped services during cleanup #674

File: Cql/CqlSdkPrototype/Elm/Extensions/ElmApiExtensions.Cql.cs (hunk 21 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Elm/Extensions/ElmApiExtensions.Cql.cs:11]: That's why the name CqlApi or ElmApi needs to have a general name that it is the starting point of the pipeline.

File: Cql/CqlSdkPrototype/GlobalUsings.cs (hunk 22 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/GlobalUsings.cs:3]: I'll add all the System and Microsoft namespaces there as a cleanup task #674

File: Cql/CqlSdkPrototype/Internal/Directories.cs (hunk 24 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Internal/Directories.cs:32]: This is only a temporary class used in the cql prototype, not meant for production.

File: Cql/CqlSdkPrototype/Internal/InternalExtensions.cs (hunk 25 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Internal/InternalExtensions.cs:33]: These extensions have a tendency to explode in size, bloating the shared libraries. Speaking from experience from previous job :)

File: Cql/CqlSdkPrototype/Internal/Maybe.cs (hunk 26 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Internal/Maybe.cs:9]: I use it in the Firely CQL SDK too. I hope Microsoft brings a more formal set of monad types into the framework

File: Cql/CqlSdkPrototype/Logging/ColorConsoleLogger.cs (hunk 27 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Logging/ColorConsoleLogger.cs:9]: This will be moved to the PackagerCLI project after the CqlSdkPrototype is removed. For now its used in both

File: Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs (hunk 30 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs]: Actually, there should be no upper boundary. When developing a new library format, and the unit tests break, a new invoker must be written on the new version.

File: Cql/Cql.Runtime/EmptyDisposable.cs (hunk 9 above)
Comment (baseTwo) [reply Cql/Cql.Runtime/EmptyDisposable.cs]: I'll remove this, I thought it wasn't possible to do a `using var disposable = a null IDisposable instance`, but that is indeed possible

File: Cql/CqlSdkPrototype/Elm/ElmApi.cs (hunk 18 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Elm/ElmApi.cs:85]: I split it up into smaller ones

File: Cql/CoreTests/PrimitiveTests.cs (hunk 5 above)
Comment (ewoutkramer) [reply Cql/CoreTests/PrimitiveTests.cs:3421]: I mean, Assert.IsTrue(true) is obviously always passing, so what is the test testing? Could you add something about the expectation in a comment above this assert.true(true), so later developers understand what this is testing?

File: Cql/CqlSdkPrototype/Cql/CqlApi.cs (hunk 11 above)
Comment (ewoutkramer) [reply Cql/CqlSdkPrototype/Cql/CqlApi.cs]: Is there any distinction left between CqlApi and its state now? Is it worth keeping two objects?

File: Cql/CqlSdkPrototype/Elm/ElmApi.cs (hunk 17 above)
Comment (ewoutkramer) [reply Cql/CqlSdkPrototype/Elm/ElmApi.cs:18]: I'll close this discussion. If we find something more appropriate for CqlApi, we can apply that here too.

File: Cql/CqlSdkPrototype/Internal/InternalExtensions.cs (hunk 25 above)
Comment (ewoutkramer) [reply Cql/CqlSdkPrototype/Internal/InternalExtensions.cs:33]: I'm just jealous I guess. I am afraid you are right based on experiences we had at Furore. I had slight hopes you fared better ;-)

File: Cql/CqlSdkPrototype/Internal/Maybe.cs (hunk 26 above)
Comment (ewoutkramer) [reply Cql/CqlSdkPrototype/Internal/Maybe.cs:9]: Yeah, but until that moment, I don't think we should introduce a variant in our pubic surface and stick to the current Microsoft designs.

File: Cql/CqlSdkPrototype/Runtime/Extensions/RuntimeApiExtensions.Cql.cs (hunk 28 above)
Comment (ewoutkramer) [reply Cql/CqlSdkPrototype/Runtime/Extensions/RuntimeApiExtensions.Cql.cs:22]: So, you want to remove all scopes in a future PR, closing this discussion.

File: Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs (hunk 30 above)
Comment (ewoutkramer) [reply Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs]: You mean to say that the IsBeween (with upper boundary Version(2,1)) should be removed from this code?

File: Demo/Test.Measures.Demo/MeasuresTest.cs (hunk 32 above)
Comment (ewoutkramer) [reply Demo/Test.Measures.Demo/MeasuresTest.cs:120]: Yes, so they are both disposable, but what does the wrapper introduce that the AssemblyLoadContext does not have?

File: Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs (hunk 30 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs]: Yes, the upper bound is removed now. If we follow semantic versioning on the code generated part, then it would be easy to put an upper limit on the version major part, but the versioning of the code generated libraries is tied to the SDK version itself. That relationship needs to be broken up

File: Cql/CqlSdkPrototype/Cql/CqlApiState.cs (hunk 12 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Cql/CqlApiState.cs]: Have a look at the latest commit. I split up options, entries and services as separate fields on the cqlapi. I'll do elmapi later

File: Cql/CoreTests/PrimitiveTests.cs (hunk 5 above)
Comment (baseTwo) [reply Cql/CoreTests/PrimitiveTests.cs:3421]: Improve the assertion

File: Cql/CqlSdkPrototype/Internal/Maybe.cs (hunk 26 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Internal/Maybe.cs:9]: Internal, wont go public

File: Demo/Test.Measures.Demo/MeasuresTest.cs (hunk 32 above)
Comment (baseTwo) [reply Demo/Test.Measures.Demo/MeasuresTest.cs:120]: Will rename to LibrarySetInvoker etc #697

File: Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs (hunk 30 above)
Comment (baseTwo) [reply Cql/CqlSdkPrototype/Runtime/Invokers/LibraryInvoker.2_0_8_0.cs]: - #698

**Review by ewoutkramer — APPROVED** [review]
All open issues discussed, many will be handled in another PR to not make merging harder.

File: Cql/CoreTests/PrimitiveTests.cs (hunk 5 above)
Comment (baseTwo) [reply Cql/CoreTests/PrimitiveTests.cs:3421]: Fixed in next PR #696
