### PR TITLE
Fix Slice implementation and add Unit tests

### LINKED ISSUE #1016: Fix Slice implementation in the engine to follow CQL specifications
Description:
The implementation of Slice method in the engine does not output sliced list as specified by below operators in CQL specification 
https://cql.hl7.org/09-b-cqlreference.html#skip
https://cql.hl7.org/09-b-cqlreference.html#tail
https://cql.hl7.org/09-b-cqlreference.html#take

Reproducing Issue and Expected Behavior:

To reproduce, below test methods can be added as part of any test class such as PrimitiveTests and executed. 
Brief is a list of four tests that exactly pulls example from above CQL specifications, with input and expected output list. Please find current output as well tagged along when these tests were run locally.

#**Test1**

```
[TestMethod]
public void Slice_for_SkipEmpty()
{
    //If the number of elements is less than zero, the result is an empty list.
    //define "SkipEmpty": Skip({ 1, 3, 5 }, -1)
    //expected output: { }
    var rtx = GetNewContext();
    var inputList = new List<int> { 1, 3, 5 };
    var expectedList = new List<int> { };
    var slicedList = rtx.Operators.Slice(inputList, -1, null);
    Assert.IsNotNull(slicedList);
    CollectionAssert.AreEqual(expectedList, slicedList.ToList());
}
```

```
**Current Output:**     
Test method CoreTests.PrimitiveTests.Slice_for_SkipEmpty threw exception: 
    System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'index')

**Expected Output:**
return an empty list of type int {}
```

#**Test2**

```
[TestMethod]
public void Slice_for_SkipNull()
{
    //If the number of elements is null, the result is the entire list, no elements are skipped.
    //define "SkipNull": Skip({ 1, 3, 5 }, null)
    //expected: { 1, 3, 5 }
    var rtx = GetNewContext();
    var inputList = new List<int> { 1, 3, 5 };
    var expectedList = new List<int> { 1, 3, 5 };
    var slicedList = rtx.Operators.Slice(inputList, null, null);
    Assert.IsNotNull(slicedList);
    CollectionAssert.AreEqual(expectedList, slicedList.ToList());
}
```
```
**Current Output:**     
Returns an empty list of type int

**Expected Output:**
{ 1, 3, 5 }
```

#**Test3**

```
[TestMethod]
public void Slice_for_Take2()
{
    //The Take operator returns the first number elements from the given list.      
    //define "Take2": Take({ 1, 2, 3, 4 }, 2)
    //expected: { 1, 2 }
    var rtx = GetNewContext();
    var inputList = new List<int> { 1, 2, 3, 4 };
    var expectedList = new List<int> { 1, 2 };
    var slicedList = rtx.Operators.Slice(inputList, 0, 2);
    Assert.IsNotNull(slicedList);
    CollectionAssert.AreEqual(expectedList, slicedList.ToList());
}
```

Output: 
```
**Current Output:**     
{1,2,3}

**Expected Output:**
{ 1, 2 }
```

#**Test4**

```
[TestMethod]
public void Slice_for_TakeEmpty()
{
    //If number is null, or 0 or less, the result is an empty list.
    //define "TakeEmpty": Take({ 1, 2, 3, 4 }, null)
    //expected: { }
    var rtx = GetNewContext();
    var inputList = new List<int> { 1, 2, 3, 4 };
    var expectedList = new List<int> { };
    var slicedList = rtx.Operators.Slice(inputList, 0, 0);
    Assert.IsNotNull(slicedList);
    CollectionAssert.AreEqual(expectedList, slicedList.ToList());
}
```
Output: 
```
**Current Output:**     
{1}

**Expected Output:**
Return an empty list of type int
```

Version:
sdk 2 develop branch

### PR DESCRIPTION
**Pull request by igajurelNCQA**
Fixes issue https://github.com/FirelyTeam/firely-cql-sdk/issues/1016

### CODE REVIEW

File: Cql/CoreTests/PrimitiveTests.cs [hunk 1]
```diff
@@ -3539,5 +3539,190 @@ public void QuantityToString()
             var s = ops.ConvertQuantityToString(new CqlQuantity(125, "cm"));
             s.Should().Be("125 'cm'");
         }
+
+        #region Slice tests
```
Comment (baseTwo) [inline Cql/CoreTests/PrimitiveTests.cs:3728]: Since there are Skip and Take operators, the tests specific to Slicing must not be ambiguous. Prefix the method names with `Slice`

File: Cql/CoreTests/PrimitiveTests.cs [hunk 2]
```diff
@@ -3539,5 +3539,190 @@ public void QuantityToString()
...
+
+        [TestCategory("SliceTests")]
+        [TestMethod]
+        public void SkipIsNull()
+        {
+            //If the source list is null, the result is null.
+            //define "SkipIsNull": Skip(null, 2)
+            var rtx = GetNewContext();
+            var inputList = null as List<int>;
+            var expectedList = null as List<int>;
```
Comment (baseTwo) [inline Cql/CoreTests/PrimitiveTests.cs:3780]: No usages of expectedList

File: Cql/CoreTests/PrimitiveTests.cs [hunk 3]
```diff
@@ -3539,5 +3539,190 @@ public void QuantityToString()
...
+
+        [TestCategory("SliceTests")]
+        [TestMethod]
+        public void TailIsNull()
+        {
+            //If the source list is null, the result is null.
+            //define "TailIsNull": Tail(null)
+            var rtx = GetNewContext();
+            var inputList = null as List<int>;
+            var expectedList = null as List<int>;
```
Comment (baseTwo) [inline Cql/CoreTests/PrimitiveTests.cs:3830]: No usages of expectedList

File: Cql/CoreTests/PrimitiveTests.cs [hunk 4]
```diff
@@ -3539,5 +3539,190 @@ public void QuantityToString()
...
+
+        [TestCategory("SliceTests")]
+        [TestMethod]
+        public void TakeIsNull()
+        {
+            //If the source list is null, the result is null.
+            //define "TakeIsNull": Take(null, 2)
+            var rtx = GetNewContext();
+            var inputList = null as List<int>;
+            var expectedList = null as List<int>;
```
Comment (baseTwo) [inline Cql/CoreTests/PrimitiveTests.cs:3882]: No usages of expectedList

File: Cql/CoreTests/PrimitiveTests.cs (hunk 1 above)
Comment (baseTwo) [inline Cql/CoreTests/PrimitiveTests.cs:3728]: Needs additional tests:
- SliceSkipZero

File: Cql/CoreTests/PrimitiveTests.cs [hunk 5]
```diff
@@ -3539,5 +3539,190 @@ public void QuantityToString()
...
+        /* Refer http://cql.hl7.org/09-b-cqlreference.html for operation details on Skip, Tail and Take cql operators 
+         * These CQL operators uses Slice semantics from http://cql.hl7.org/04-logicalspecification.html#slice
+        */
+
+        [TestCategory("SliceTests")]
+        [TestMethod]
+        public void Skip2()
+        {
+            //The Skip operator returns the elements in the list, skipping the first number elements. 
+            //define "Skip2": Skip({ 1, 2, 3, 4, 5 }, 2) // { 3, 4, 5 }
```
Comment (baseTwo) [inline Cql/CoreTests/PrimitiveTests.cs:3738]: The cql refers to the Skip operator which maps to ICqlOperators.ListSkip. Do we have cql example that maps to Slice?

File: Cql/CoreTests/PrimitiveTests.cs [hunk 6]
```diff
@@ -3539,5 +3539,190 @@ public void QuantityToString()
...
+            var slicedList = rtx.Operators.Slice(inputList, 2, null);
+            Assert.IsNull(slicedList);
+        }
+
+        [TestCategory("SliceTests")]
+        [TestMethod]
+        public void Tail234()
+        {
+            //The Tail operator returns all but the first element from the given list. 
+            //define "Tail234": Tail({ 1, 2, 3, 4 }) // { 2, 3, 4 }
```
Comment (baseTwo) [inline Cql/CoreTests/PrimitiveTests.cs:3801]: The cql refers to the Tail operator which maps to ICqlOperators.Tail. Do we have cql example that maps to Slice?

File: Cql/CoreTests/PrimitiveTests.cs [hunk 7]
```diff
@@ -3539,5 +3539,190 @@ public void QuantityToString()
...
+            var rtx = GetNewContext();
+            var inputList = null as List<int>;
+            var expectedList = null as List<int>;
+            var slicedList = rtx.Operators.Slice(inputList, 0, 2);
+            Assert.IsNull(slicedList);
+        }
+
+        [TestCategory("SliceTests")]
+        [TestMethod]
+        public void Slice_array_source()
```
Comment (baseTwo) [inline Cql/CoreTests/PrimitiveTests.cs]: No benefit in adding tests for array or linkedlist sources

**Review by baseTwo — CHANGES_REQUESTED** [review]

**Comment by baseTwo** [comment]
Although this PR only focuses on the Slice operator, the issue speaks to Skip, Tail and Take also. I noticed those are also not complying with the spec:

e.g. 
For Skip the spec rule is "If the number of elements is null, the result is the entire list, no elements are skipped."
But in the C# `null` is returned if the number of elements is `null`, and it should have returned the whole list

```csharp
public IEnumerable<T>? ListSkip<T>(IEnumerable<T> argument, int? number)
{
    if (argument == null || number == null) return null;
    else return argument
            .Skip(number.Value)
            .ToList();
}
```

The same applies for `ListTake`

File: Cql/Cql.Runtime/Operators/CqlOperators.ListOperators.cs [hunk 8]
```diff
@@ -1047,26 +1047,23 @@ internal partial class CqlOperators
...
             if (source == null)
                 return null;
-            if ((startIndex == null && endIndex == null) || !source.Any())
-            {
-                return [];
-            }
-            var si = startIndex ?? 0;
-            if (source is List<T> list)
+
+            if (!source.Any())
```
Comment (baseTwo) [inline Cql/Cql.Runtime/Operators/CqlOperators.ListOperators.cs:1051]: This check is unnecessary. A call to Any is _potentially_ expensive when it has to enumerate when a Count is not available

File: Cql/CoreTests/PrimitiveTests.cs (hunk 5 above)
Comment (igajurelNCQA) [reply Cql/CoreTests/PrimitiveTests.cs:3738]: With the Cql to Elm translation, the Skip, Tail and Take operators are being mapped into Slice properties in the Elm, which then uses the sdk implementation of Slice. Please refer to attached text file where I have added example of Cql for Skip, Take, Tail operaions; translated ELM; and generated C# content, which uses Slice method. So, the ListSkip, ListTake, ListTail these are not being mapped into and/or used based on given CQLs
[cql-el-csharp-artifacts.txt](https://github.com/user-attachments/files/22284854/cql-el-csharp-artifacts.txt)

File: Cql/CoreTests/PrimitiveTests.cs (hunk 6 above)
Comment (igajurelNCQA) [reply Cql/CoreTests/PrimitiveTests.cs:3801]: please see above comment for example.

**Comment by baseTwo** [comment]
@igajurelNCQA , could you have a look at fixing the merge conflicts and the comments?

**Comment by igajurelNCQA** [comment]
> @igajurelNCQA , could you have a look at fixing the merge conflicts and the comments?

I resolved the merge conflicts. I moved this to to draft since I need some more time to resolve the comments.

File: Cql/CoreTests/PrimitiveTests.cs (hunk 2 above)
Comment (igajurelNCQA) [reply Cql/CoreTests/PrimitiveTests.cs:3780]: resolved

File: Cql/CoreTests/PrimitiveTests.cs (hunk 4 above)
Comment (igajurelNCQA) [reply Cql/CoreTests/PrimitiveTests.cs:3882]: resolved

File: Cql/CoreTests/PrimitiveTests.cs (hunk 7 above)
Comment (igajurelNCQA) [reply Cql/CoreTests/PrimitiveTests.cs]: resolved

File: Cql/CoreTests/PrimitiveTests.cs (hunk 3 above)
Comment (igajurelNCQA) [reply Cql/CoreTests/PrimitiveTests.cs:3830]: resolved

File: Cql/CoreTests/PrimitiveTests.cs (hunk 1 above)
Comment (igajurelNCQA) [reply Cql/CoreTests/PrimitiveTests.cs:3728]: Added one based on the context drawn from the test name you suggested. Let me know if you meant something else to verify in the test.

**Comment by igajurelNCQA** [comment]
> is returned if the number of elements i

@baseTwo Regarding this one, do you still think these methods should be updated given the cql example I shared earlier invokes just the Slice method in compiled lambdas and not the ListTake, ListTail methods. 

Also, are the Copilot comments a must-fix rule in firely PR policy? Let me know if those generated ones above from CoPilot is something you want me to update.

**Comment by baseTwo** [comment]
> > is returned if the number of elements i
> 
> @baseTwo Regarding this one, do you still think these methods should be updated given the cql example I shared earlier invokes just the Slice method in compiled lambdas and not the ListTake, ListTail methods.

Yes, we need to update those methods as well, but I'm fine with doing this as a separate PR

> 
> Also, are the Copilot comments a must-fix rule in firely PR policy? Let me know if those generated ones above from CoPilot is something you want me to update.

If I don't agree with the Copilot comments, I will resolve them, so those that are currently remaining are valid comments I agree with.

File: Cql/Cql.Runtime/Operators/CqlOperators.ListOperators.cs [hunk 9]
```diff
@@ -1047,26 +1047,23 @@ internal partial class CqlOperators
...
+                return Enumerable.Empty<T>();
+
+            if (startIndex == null && endIndex == null)
+                return source;
+
+            if (startIndex < 0 || endIndex <= 0)
```
[the remark this answers is not in the document]
Comment (igajurelNCQA) [reply Cql/Cql.Runtime/Operators/CqlOperators.ListOperators.cs:1057]: Per Take operation https://cql.hl7.org/09-b-cqlreference.html#take, If number is null, **or 0** or less, **the result is an empty list.**
Hence, when the input number is 0 in a Take operation, the resulting Slice operation sets endIndex as 0 and for such case, empty list should be returned, therefore we need to check endIndex <= 0 here.

This has been tested as part of below Test

```
        [TestMethod]
        public void SliceTakeEmpty()
        {
            //If number is null, or 0 or less, the result is an empty list.
            //define "TakeEmpty": Take({ 1, 2, 3, 4 }, null) // { }
            var rtx = GetNewContext();
            var inputList = new List<int> { 1, 2, 3, 4 };
            var expectedList = new List<int> { };
            var slicedList = rtx.Operators.Slice(inputList, 0, 0);
            Assert.IsNotNull(slicedList);
            CollectionAssert.AreEqual(expectedList, slicedList.ToList());
        }
```

File: Cql/Cql.Runtime/Operators/CqlOperators.ListOperators.cs [hunk 10]
```diff
@@ -1047,26 +1047,23 @@ internal partial class CqlOperators
...
+                return source.Skip(startIndex ?? 0).ToList();
             }
             else
             {
-                var skip = source.Skip(si);
-                var result = new List<T>();
-                foreach (var item in skip.Take(endIndex ?? int.MaxValue))
-                    result.Add(item);
-                return result;
+                return source.Skip(startIndex ?? 0).Take((endIndex ?? 0) - (startIndex ?? 0)).ToList();
```
[the remark this answers is not in the document]
Comment (igajurelNCQA) [reply Cql/Cql.Runtime/Operators/CqlOperators.ListOperators.cs]: This will likely not happen since the if(endIndex==null) handles and returns desired list. But this looks more like a sanity fix to make sure that under any manipulation inside else block if endIndex is then set to null, it does not always default to 0 and returns Take(0-startIndex) => Take(-startIndex) and give an empty list, which is not the intent of this block. Hence, accepting this fix.

**Comment by igajurelNCQA** [comment]
Current ELMs are directly mapping Skip, Tail and Take CQL operators into Slice operator. Hence, the Slice operator fixes should suffice. But downstream, if ELMs are to change and we have a direct 1:1 mapping with these ListSkip, Tail, ListTake methods, then the suggested fixes could help avoid future bugs. 
Note
- for ListSkip, it is correct that "If the number of elements is null, the result is the entire list, no elements are skipped." 
- So, I have made a fix to return original input.

- But, for ListTake, its not the same. Take definition (https://cql.hl7.org/09-b-cqlreference.html#take) says If number is null, or 0 or less, the result is an empty list.
- So, I have made a fix to return empty list as output.



> Although this PR only focuses on the Slice operator, the issue speaks to Skip, Tail and Take also. I noticed those are also not complying with the spec:
> 
> e.g. For Skip the spec rule is "If the number of elements is null, the result is the entire list, no elements are skipped." But in the C# `null` is returned if the number of elements is `null`, and it should have returned the whole list
> 
> ```cs
> public IEnumerable<T>? ListSkip<T>(IEnumerable<T> argument, int? number)
> {
>     if (argument == null || number == null) return null;
>     else return argument
>             .Skip(number.Value)
>             .ToList();
> }
> ```
> 
> The same applies for `ListTake`

**Comment by baseTwo** [comment]
@igajurelNCQA , I will approve this with the outstanding comment and just create another ticket to fix it later.

**Review by baseTwo — APPROVED** [review]

File: Cql/Cql.Runtime/Operators/CqlOperators.ListOperators.cs (hunk 8 above)
Comment (baseTwo) [reply Cql/Cql.Runtime/Operators/CqlOperators.ListOperators.cs:1051]: Will do this in #1029
